---
title: "data_viz"
author: "anjie & gal"
date: "2/17/2022"
output: html_document
---

```{r}
library(here)
library(tidyverse)
d <- read_csv(here("data.csv"), col_names = TRUE)
```

```{r}
d <- d %>% 
  select(Subject, Session, CatType, FamType, Group, NumLooks, NumLeftLooks, LeftType, NumRightLooks, RightType, FamiliarPosition, Procedure) %>% 
  mutate(
    FamType = case_when(
      FamType == "Courte" ~ "short", 
      FamType == "Longue" ~ "long" 
    ),
    look_at_fam = case_when(
    FamiliarPosition == "Left" ~ NumLeftLooks, 
    FamiliarPosition == "Right" ~ NumRightLooks, 
    TRUE ~ NA_real_
  ), 
    look_at_novel = case_when(
    FamiliarPosition == "Left" ~ NumRightLooks, 
    FamiliarPosition == "Right" ~ NumLeftLooks, 
    TRUE ~ NA_real_
  )) %>% 
  pivot_longer(cols = c("look_at_fam", "look_at_novel"), 
               names_to = "look_type", 
               values_to = "num_look")
```


```{r}
d %>% 
  filter(!is.na(num_look)) %>% 
  group_by(Subject, Session, look_type) %>% 
  mutate(
    test_trial = row_number()
  ) %>% 
  ggplot(aes(x = test_trial, y = num_look, color = look_type)) + 
 # geom_point(alpha = .3) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .5)) + 
  facet_wrap(CatType~FamType)+
  scale_x_continuous(breaks = seq(1, 10, 1)) +
  theme_classic()
```

```{r}
d %>% 
  filter(!is.na(num_look)) %>% 
  group_by(Subject, Session, look_type) %>% 
  mutate(
    test_trial = row_number()
  ) %>% 
  filter(Session == 1) %>% 
  ggplot(aes(x = test_trial, y = num_look, color = look_type)) + 
 # geom_point(alpha = .3) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .5)) + 
  facet_wrap(CatType~FamType)+
  scale_x_continuous(breaks = seq(1, 10, 1)) +
  theme_classic()

```


```{r}
d %>% 
  filter(is.na(num_look)) %>% 
  group_by(Subject, Session, look_type) %>% 
  mutate(
    test_trial = row_number()
  ) %>% 
  ggplot(aes(x = test_trial, y = NumLooks)) + 
 # geom_point(alpha = .3) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .5)) + 
  facet_wrap(CatType~FamType)+
  #scale_x_continuous(breaks = seq(1, 10, 1)) +
  theme_classic()
```

